### ISSUE TITLE
Adding to bioconda

### ISSUE THREAD

**Issue by TomHarrop** [Dmitry-Antipov/viral-metflye-supplementary#3]
I've drafted a recipe for viralFlye at https://github.com/bioconda/bioconda-recipes/pull/39987.

Please let me know if there are any issues.

**Comment by mikolmogorov** [comment]
Thank you! @Dmitry-Antipov maybe add the reference to bioconda package to Readme?

**Comment by Dmitry-Antipov** [comment]
missed the thread, added.
