### ISSUE TITLE
Flye assembly directory not found

### ISSUE THREAD

**Issue by samuelmontgomery** [Dmitry-Antipov/viral-metflye-supplementary#5]
Hi, 

I cannot get viralFlye to run when pointing to my flye assembly directory with both absolute or relative paths, and running from multiple locations

Is it supposed to just be to the directory itself, or a specific folder within the directory?
I ran Flye with the --meta flag enabled, but am having no luck getting it to work

Thanks!

**Comment by Dmitry-Antipov** [comment]
Hi,
That's strange, there should be no specific requirements if you provide the path. Could you show me your command line for run and the error message?

**Comment by samuelmontgomery** [comment]
Sure - see below

`/home/ubuntu/scratch/software/viralFlye/viralFlye.py --dir "/home/ubuntu/scratch/analysis/nbd_phage/phage_4C8D/flye" --hmm "/home/ubuntu/scratch/references/pham/Pfam-A.hmm.gz" --reads "/home/ubuntu/scratch/analysis/nbd_phage/phage_4C8D/phage_4C8D_filtered.fastq" --outdir "/home/ubuntu/scratch/analysis/nbd_phage/phage_4C8D/viralflye"`

`Flye assembly directory not found:  /home/ubuntu/scratch/analysis/nbd_phage/phage_4C8D/flye`

I have tried relative and absolute paths as well for the inputs

**Comment by samuelmontgomery** [comment]
figured it out - I am running multiple samples at a time and for downstream processes am renaming the flye assembly file "assembly.fasta" with the name of my sample at flye output
changing it to assembly.fasta works great
